version: "3.8"
services:
  neo4j:
    image: neo4j:4.4.3-community
    ports:
      - 7888:7474
      - 7999:7687
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins
